-- MySQL Script generated by MySQL Workbench
-- 09/16/16 17:42:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `i_customer` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `status` ENUM('Closed', 'Suspended', 'Active') NOT NULL,
  `first_name` VARCHAR(200) NULL,
  `last_name` VARCHAR(200) NULL,
  `address` TEXT NULL,
  `state` VARCHAR(150) NULL,
  `city` VARCHAR(150) NULL,
  `post_code` VARCHAR(150) NULL,
  `country` VARCHAR(150) NULL,
  `Tel1` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Tel2` VARCHAR(45) NULL,
  PRIMARY KEY (`i_customer`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sites` (
  `i_site` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `address` VARCHAR(150) NULL,
  `state` VARCHAR(150) NULL,
  `city` VARCHAR(150) NULL,
  `post_code` VARCHAR(150) NULL,
  `tel` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `i_customer` BIGINT NOT NULL,
  `email` VARCHAR(150) NULL,
  PRIMARY KEY (`i_site`, `i_customer`),
  INDEX `fk_Sites_Customers1_idx` (`i_customer` ASC),
  CONSTRAINT `fk_Sites_Customers1`
    FOREIGN KEY (`i_customer`)
    REFERENCES `mydb`.`Customers` (`i_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `i_user` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `login` VARCHAR(150) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NULL,
  `i_customer` BIGINT NOT NULL,
  `super_admin` ENUM('Y', 'N') NULL,
  `root_user` ENUM('Y', 'N') NULL,
  PRIMARY KEY (`i_user`, `i_customer`),
  INDEX `fk_Users_Customers1_idx` (`i_customer` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  CONSTRAINT `fk_Users_Customers1`
    FOREIGN KEY (`i_customer`)
    REFERENCES `mydb`.`Customers` (`i_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sellers` (
  `i_seller` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `first_name` VARCHAR(200) NULL,
  `last_name` VARCHAR(200) NULL,
  `address` TEXT NULL,
  `state` VARCHAR(150) NULL,
  `city` VARCHAR(150) NULL,
  `post_code` VARCHAR(150) NULL,
  `country` VARCHAR(150) NULL,
  `Tel` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `i_customer` BIGINT NOT NULL,
  PRIMARY KEY (`i_seller`, `i_customer`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_Sellers_Customers1_idx` (`i_customer` ASC),
  CONSTRAINT `fk_Sellers_Customers1`
    FOREIGN KEY (`i_customer`)
    REFERENCES `mydb`.`Customers` (`i_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Properties` (
  `i_property` BIGINT NOT NULL,
  `code` VARCHAR(150) NULL,
  `description` TEXT NULL,
  `address` TEXT NULL,
  `city` VARCHAR(150) NULL,
  `state` VARCHAR(150) NULL,
  `i_seller` BIGINT NOT NULL,
  `i_customer` BIGINT NOT NULL,
  `status` ENUM('Closed', 'InMarket', 'UnderOffer', 'Withdrawn', 'OnHold') NULL,
  `country` VARCHAR(150) NULL,
  `Price` DECIMAL NULL,
  PRIMARY KEY (`i_property`, `i_seller`, `i_customer`),
  INDEX `fk_Properties_Sellers1_idx` (`i_seller` ASC, `i_customer` ASC),
  CONSTRAINT `fk_Properties_Sellers1`
    FOREIGN KEY (`i_seller` , `i_customer`)
    REFERENCES `mydb`.`Sellers` (`i_seller` , `i_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AgentProperties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AgentProperties` (
  `i_property` BIGINT NOT NULL,
  `i_seller` BIGINT NOT NULL,
  `i_customer` BIGINT NOT NULL,
  `Users_i_user` BIGINT NOT NULL,
  `Users_i_site` BIGINT NOT NULL,
  `Users_i_customer` BIGINT NOT NULL,
  PRIMARY KEY (`i_property`, `i_seller`, `i_customer`, `Users_i_user`, `Users_i_site`, `Users_i_customer`),
  INDEX `fk_Properties_has_Sites_Properties1_idx` (`i_property` ASC, `i_seller` ASC, `i_customer` ASC),
  INDEX `fk_AgentProperties_Users1_idx` (`Users_i_user` ASC, `Users_i_site` ASC, `Users_i_customer` ASC),
  CONSTRAINT `fk_Properties_has_Sites_Properties1`
    FOREIGN KEY (`i_property` , `i_seller` , `i_customer`)
    REFERENCES `mydb`.`Properties` (`i_property` , `i_seller` , `i_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AgentProperties_Users1`
    FOREIGN KEY (`Users_i_user`)
    REFERENCES `mydb`.`Users` (`i_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prospects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prospects` (
  `i_prospect` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `first_name` VARCHAR(200) NULL,
  `last_name` VARCHAR(200) NULL,
  `address` TEXT NULL,
  `state` VARCHAR(150) NULL,
  `city` VARCHAR(150) NULL,
  `post_code` VARCHAR(150) NULL,
  `country` VARCHAR(150) NULL,
  `Tel` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `i_customer` BIGINT NOT NULL,
  PRIMARY KEY (`i_prospect`, `i_customer`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_Prospects_Customers1_idx` (`i_customer` ASC),
  CONSTRAINT `fk_Prospects_Customers1`
    FOREIGN KEY (`i_customer`)
    REFERENCES `mydb`.`Customers` (`i_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Offers` (
  `i_offer` BIGINT NOT NULL AUTO_INCREMENT,
  `details` TEXT NULL,
  `date` DATE NOT NULL,
  `price` DECIMAL NOT NULL,
  `status` ENUM('Pending', 'Refused', 'Accepted') NULL,
  `i_property` BIGINT NOT NULL,
  `i_seller` BIGINT NOT NULL,
  `i_customer` BIGINT NOT NULL,
  `i_prospect` BIGINT NOT NULL,
  PRIMARY KEY (`i_offer`, `i_property`, `i_seller`, `i_customer`, `i_prospect`),
  INDEX `fk_Offers_Properties1_idx` (`i_property` ASC, `i_seller` ASC, `i_customer` ASC),
  INDEX `fk_Offers_Prospects1_idx` (`i_prospect` ASC),
  CONSTRAINT `fk_Offers_Properties1`
    FOREIGN KEY (`i_property` , `i_seller` , `i_customer`)
    REFERENCES `mydb`.`Properties` (`i_property` , `i_seller` , `i_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offers_Prospects1`
    FOREIGN KEY (`i_prospect`)
    REFERENCES `mydb`.`Prospects` (`i_prospect`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Views`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Views` (
  `i_view` BIGINT NOT NULL AUTO_INCREMENT,
  `time` DATETIME NOT NULL,
  `status` ENUM('Cancelled', 'Done', 'Scheduled') NULL,
  `i_user` BIGINT NOT NULL,
  `i_property` BIGINT NOT NULL,
  `i_seller` BIGINT NOT NULL,
  `i_prospect` BIGINT NOT NULL,
  `i_customer` BIGINT NOT NULL,
  PRIMARY KEY (`i_view`, `i_user`, `i_property`, `i_seller`, `i_prospect`, `i_customer`),
  INDEX `fk_Views_Agents1_idx` (`i_user` ASC),
  INDEX `fk_Views_Properties1_idx` (`i_property` ASC, `i_seller` ASC),
  INDEX `fk_Views_Prospects1_idx` (`i_prospect` ASC, `i_customer` ASC),
  CONSTRAINT `fk_Views_Agents1`
    FOREIGN KEY (`i_user`)
    REFERENCES `mydb`.`Users` (`i_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Views_Properties1`
    FOREIGN KEY (`i_property` , `i_seller`)
    REFERENCES `mydb`.`Properties` (`i_property` , `i_seller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Views_Prospects1`
    FOREIGN KEY (`i_prospect` , `i_customer`)
    REFERENCES `mydb`.`Prospects` (`i_prospect` , `i_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SiteUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SiteUsers` (
  `i_siteuser` BIGINT NOT NULL AUTO_INCREMENT,
  `i_site` BIGINT NOT NULL,
  `i_customer` BIGINT NOT NULL,
  `i_user` BIGINT NOT NULL,
  `is_site_admin` ENUM('Y', 'N') NOT NULL DEFAULT 'N',
  PRIMARY KEY (`i_siteuser`, `i_site`, `i_customer`, `i_user`),
  INDEX `fk_SiteUsers_Users1_idx` (`i_user` ASC),
  CONSTRAINT `fk_SiteUsers_Sites1`
    FOREIGN KEY (`i_site` , `i_customer`)
    REFERENCES `mydb`.`Sites` (`i_site` , `i_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SiteUsers_Users1`
    FOREIGN KEY (`i_user`)
    REFERENCES `mydb`.`Users` (`i_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OfferComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OfferComments` (
  `i_offercomment` BIGINT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NULL,
  `comment` TEXT NULL,
  `i_offer` BIGINT NOT NULL,
  `i_property` BIGINT NOT NULL,
  `i_seller` BIGINT NOT NULL,
  `i_customer` BIGINT NOT NULL,
  `i_prospect` BIGINT NOT NULL,
  `author_id` BIGINT NULL,
  `author_type` ENUM('User', 'Seller') NULL,
  PRIMARY KEY (`i_offercomment`, `i_offer`, `i_property`, `i_seller`, `i_customer`, `i_prospect`),
  INDEX `fk_OfferComments_Offers1_idx` (`i_offer` ASC, `i_property` ASC, `i_seller` ASC, `i_customer` ASC, `i_prospect` ASC),
  CONSTRAINT `fk_OfferComments_Offers1`
    FOREIGN KEY (`i_offer` , `i_property` , `i_seller` , `i_customer` , `i_prospect`)
    REFERENCES `mydb`.`Offers` (`i_offer` , `i_property` , `i_seller` , `i_customer` , `i_prospect`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PropertiesComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PropertiesComments` (
  `i_propertycomments` BIGINT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NULL,
  `Comment` TEXT NULL,
  `i_property` BIGINT NOT NULL,
  `i_seller` BIGINT NOT NULL,
  `i_customer` BIGINT NOT NULL,
  `author_id` BIGINT NULL,
  `author_type` ENUM('User', 'Seller') NULL,
  PRIMARY KEY (`i_propertycomments`, `i_property`, `i_seller`, `i_customer`),
  INDEX `fk_PropertiesComments_Properties1_idx` (`i_property` ASC, `i_seller` ASC, `i_customer` ASC),
  CONSTRAINT `fk_PropertiesComments_Properties1`
    FOREIGN KEY (`i_property` , `i_seller` , `i_customer`)
    REFERENCES `mydb`.`Properties` (`i_property` , `i_seller` , `i_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ViewsComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ViewsComments` (
  `i_viewcomment` BIGINT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NULL,
  `Comment` TEXT NULL,
  `author_id` BIGINT NULL,
  `author_type` ENUM('User', 'Seller') NULL,
  `i_view` BIGINT NOT NULL,
  `i_user` BIGINT NOT NULL,
  `i_property` BIGINT NOT NULL,
  `i_seller` BIGINT NOT NULL,
  `i_prospect` BIGINT NOT NULL,
  `i_customer` BIGINT NOT NULL,
  PRIMARY KEY (`i_viewcomment`),
  INDEX `fk_ViewsComments_Views1_idx` (`i_view` ASC, `i_user` ASC, `i_property` ASC, `i_seller` ASC, `i_prospect` ASC, `i_customer` ASC),
  CONSTRAINT `fk_ViewsComments_Views1`
    FOREIGN KEY (`i_view` , `i_user` , `i_property` , `i_seller` , `i_prospect` , `i_customer`)
    REFERENCES `mydb`.`Views` (`i_view` , `i_user` , `i_property` , `i_seller` , `i_prospect` , `i_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`api_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_users` (
  `i_api_user` BIGINT NOT NULL,
  `login` VARCHAR(150) NULL,
  `pasword` VARCHAR(150) NULL,
  PRIMARY KEY (`i_api_user`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`api_users_customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_users_customers` (
  `i_customer` BIGINT NOT NULL,
  `i_api_user` BIGINT NOT NULL,
  PRIMARY KEY (`i_customer`, `i_api_user`),
  INDEX `fk_api_users_customers_table11_idx` (`i_api_user` ASC),
  CONSTRAINT `fk_api_users_customers_Customers1`
    FOREIGN KEY (`i_customer`)
    REFERENCES `mydb`.`Customers` (`i_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_api_users_customers_table11`
    FOREIGN KEY (`i_api_user`)
    REFERENCES `mydb`.`api_users` (`i_api_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
